services:
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - PORT=${BACKEND_PORT:-3000}
      - DATABASE_URL=${DATABASE_URL}
      - BASE_URL=${BASE_URL}
      - BLACKBOX_API_KEY=${BLACKBOX_API_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_REGION=${S3_REGION}
    env_file:
      - .env

  frontend:
    build: ./frontend/hack-your-cv
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    volumes:
      - ./frontend/hack-your-cv/src:/app/src
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000}
    env_file:
      - .env
